clear;
% load('features.mat');
tic
[feature_a,Target]=sqz1(alexnet,'fc8');
[feature_res,Target]=sqz1(resnet18,'fc1000');
[feature_m,Target]=sqz1(mobilenetv2,'Logits');
time=toc;
hiddenSize=600;
maxepoch=100;
autoenc1 = trainAutoencoder(feature_a,hiddenSize,'MaxEpochs',maxepoch, ...
    'L2WeightRegularization',0.001, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.05, ...
    'DecoderTransferFunction','purelin');
f_a = encode(autoenc1,feature_a);
autoenc2 = trainAutoencoder(feature_res,hiddenSize,'MaxEpochs',maxepoch, ...
    'L2WeightRegularization',0.001, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.05, ...
    'DecoderTransferFunction','purelin');
f_res = encode(autoenc2,feature_res);
autoenc3 = trainAutoencoder(feature_m,hiddenSize, 'MaxEpochs',maxepoch,...
    'L2WeightRegularization',0.001, ...
    'SparsityRegularization',4, ...
    'SparsityProportion',0.05, ...
    'DecoderTransferFunction','purelin');
f_m = encode(autoenc3,feature_m);
Input=[f_a; f_res; f_m];
% Input=[feature_a; feature_res; feature_m];
